anaxago_core:
    resource: "@AnaxagoCoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults: { _controller: AnaxagoCoreBundle:Security:login }

logout:
    path: /logout

anaxago_core_registration:
    path: /register
    defaults: { _controller: AnaxagoCoreBundle:Security:registration }

projects:
    path: /projects
    defaults: { _controller: AnaxagoCoreBundle:api:getProjects}

money:
    path: /money/key={keyapi}/idProject={idp}/montant={sum}
    defaults: { _controller: AnaxagoCoreBundle:api:getfav}